package dev.sebastiano.bioparco.recordings

import java.nio.file.Files
import java.nio.file.Path

object ReadmeEnclosures {
    const val START = "<!-- enclosures:start -->"
    const val END = "<!-- enclosures:end -->"

    fun render(published: Map<String, PublishedSpecimen>): String {
        val rows =
            Enclosures.all.joinToString("\n") { enclosure ->
                val url = published.getValue(enclosure.module).url
                """    <tr>
      <td><a href="${enclosure.module}/">${enclosure.title}</a></td>
      <td>${enclosure.creditHtml}</td>
      <td><video src="$url" width="280" controls muted playsinline></video></td>
    </tr>"""
            }
        return """$START
<table>
  <thead>
    <tr>
      <th>Specimen</th>
      <th>Author / reference</th>
      <th>Recording</th>
    </tr>
  </thead>
  <tbody>
$rows
  </tbody>
</table>
$END"""
    }

    fun replace(readme: String, published: Map<String, PublishedSpecimen>): String {
        val table = render(published)
        if (readme.contains(START) && readme.contains(END)) {
            val start = readme.indexOf(START)
            val end = readme.indexOf(END) + END.length
            return readme.substring(0, start) + table + readme.substring(end)
        }
        val heading = "## Enclosures"
        val headingAt = readme.indexOf(heading)
        check(headingAt >= 0) { "README is missing '$heading'" }
        val afterHeading = headingAt + heading.length
        val nextHeading = readme.indexOf("\n## ", afterHeading)
        val tail = if (nextHeading >= 0) readme.substring(nextHeading) else ""
        return readme.substring(0, afterHeading).trimEnd() +
            "\n\n" +
            table +
            "\n\n" +
            tail.trimStart()
    }

    fun write(repoRoot: Path) {
        val readme = repoRoot.resolve("README.md")
        val published = PublishedManifest.load(repoRoot.resolve("recordings/published.json"))
        Files.writeString(readme, replace(Files.readString(readme), published))
        Enclosures.all.forEach { enclosure ->
            val url = published.getValue(enclosure.module).url
            rewriteSpecimenReadme(repoRoot.resolve(enclosure.module).resolve("README.md"), url)
        }
    }

    private fun rewriteSpecimenReadme(path: Path, url: String) {
        if (!Files.isRegularFile(path)) return
        val text = Files.readString(path)
        val replacement =
            """
            ## Recording

            Auto-generated by Spectre:

            $url
            """
                .trimIndent()
        val updated =
            Regex("""## Recording\n\nAuto-generated by Spectre:\n\nhttps://\S+""")
                .replace(text, replacement)
        Files.writeString(path, updated)
    }
}
